---
title: "Likert scales on technology and mechainisation"
author: "mz"
date: "21.2.2017"
output:
  pdf_document:
  number_sections: yes
toc: yes
toc_depth: 3
html_document: default
word_document:
  reference_docx: StyleReference.docx
word_document html_document: default
---


```{r setup}
library(dplyr)
library(lattice)
require(grid)
require(latticeExtra)
require(HH)
getwd()
# load("../data/survey.dataframe.RData")
```




sgbar.likert <- prop.table(table(data$q57a))*100
sgbar.likert<- rbind(sgbar.likert, prop.table(table(data$q57b))*100)
sgbar.likert<- rbind(sgbar.likert, prop.table(table(data$q57c))*100)
sgbar.likert<- rbind(sgbar.likert, prop.table(table(data$q57d))*100)

rownames(sgbar.likert) <- c("Higher yield", "Ease of farming", "Soil quality", "Crop quality")


likert(as.matrix(sgbar.likert),
       main='Do you thing using agricultural machinery can lead to:',
       xlab="Percentage")


sgbar.likert <- prop.table(table(data$n151,data$q57a),1)*100

likert(as.matrix(sgbar.likert),
       main='Do you thing using agricultural machinery can lead to higher yields',
       xlab="Percentage")


sgbar.likert <- prop.table(table(data$n151,data$q57b),1)*100

likert(as.matrix(sgbar.likert),
       main='Do you thing using agricultural machinery can lead to incresed ease of farming',
       xlab="Percentage")

sgbar.likert <- prop.table(table(data$n151,data$q57c),1)*100

likert(as.matrix(sgbar.likert),
       main='Do you thing using agricultural machinery can lead to incresed soil quality',
       xlab="Percentage")

sgbar.likert <- prop.table(table(data$n151,data$q57d),1)*100

likert(as.matrix(sgbar.likert),
       main='Do you thing using agricultural machinery can lead to incresed crop quality',
       xlab="Percentage")
```