---
title: "Ken - extra queries 5.12.18 - HH structure and HH labour -- Myanmar survey"
tables: yes
output:
  html_document:
  toc: yes
---

```{r setup, echo = FALSE, warning = FALSE, message = FALSE}
library(knitr)
library(dplyr)
load("../data/survey.data03.RData")
source("../scripts/R05-MyFunctions.R")
```

### Household structure by age group


`r var <- dataset$n201`
#### `r description(I(var))`

[N = `r sum(!is.na(var))`] 

```{r results='asis', echo=FALSE, fig.height=6}

Fun05PrintTab.region(var)
FunR05Barplot.age(var) 
```



`r var <- dataset$n203`
#### `r description(I(var))`

[N = `r sum(!is.na(var))`] 

```{r results='asis', echo=FALSE, fig.height=6}

Fun05PrintTab.region(var)
FunR05Barplot.age(var) 
```

`r var <- dataset$n205`
#### `r description(I(var))`

[N = `r sum(!is.na(var))`] 

```{r results='asis', echo=FALSE, fig.height=6}

Fun05PrintTab.region(var)
FunR05Barplot.age(var) 
```

## Household strucutre by age and gender of head of household


`r var <- dataset$n201`
#### `r description(I(var))`

[N = `r sum(!is.na(var))`] 

```{r results='asis', echo=FALSE, fig.height=6}

Fun06PrintTab.region(var)
FunR06Barplot.age(var) 
```


`r var <- dataset$n203`
#### `r description(I(var))`

[N = `r sum(!is.na(var))`] 

```{r results='asis', echo=FALSE, fig.height=6}

Fun06PrintTab.region(var)
FunR06Barplot.age(var) 
```



`r var <- dataset$n205`
#### `r description(I(var))`

[N = `r sum(!is.na(var))`] 

```{r results='asis', echo=FALSE, fig.height=6}

Fun06PrintTab.region(var)
FunR06Barplot.age(var) 
```

