---
title: "Myanmar Survey Analysis - MZ"
author: "mz"
date: "5.2.2017"
output:
  pdf_document:
  number_sections: yes
toc: yes
toc_depth: 3
html_document: default
word_document:
  reference_docx: StyleReference.docx
word_document html_document: default
---
  
# Survey Data Analysis Journal
  
## Sunday 5.2.2017 - First trawl - Univariate descriptives
  
Clean dataset arrived 30.1.2017, in .sav format. 

Installed SPSS for quick analysis, but waited for MSR report, which arrived 1.2. in hope that it may already include a descriptive analysis, but it did not. It is a pure technical report about sampling etc. To feed into methodology section. 

Original copy of data kept raw in `survey\data\raw.original.data`.

Prepare web report of univariate distributions of variables - to degree sensible. 

* remove `Q3_OT_SP` other marital status as no valid answers were given. 
* remove `Q4_96_OT_SP` other educational grade/level as no valid answers were given. 
* New variable `N1` sums up all seven disability questions Q6_A to Q6_G as number of dificulties reported, max is seven. Checks out with 'Q6_H` which reports who doesn't have any disabilities. 
* **ISSUE** - `Q7_5` on working outside of the village part of the year is wrongly coded - 1 for yes and 2 for no. Recoded all to 1 for yes and 0 for no. 
* New variable `N2` - number of hh members working outside of village part of the year. from `Q7_5$1` to `Q7_5$14`
* New variable `N3` - number of hh members working in village in same township. From  `Q7_6$1` to `Q7_6$14`
* New variable `N4` - number of hh members working in different township. From  `Q7_6$1` to `Q7_6$14``
* New variable `N5` - number of hh members working in city in Myanmar (eg Mandalay, Yangon).From  `Q7_6$1` to `Q7_6$14`
* New variable `N6` - number of hh members working outside Myanmar. From  `Q7_6$1` to `Q7_6$14`
* New variable `N7` - number of hh members that have moved out that are spouses - relationship value from  `Q8_1$1` to `Q8_1$14`
* New variable `N8` - number of hh members that have moved out that are children - relationship value from  `Q8_1$1` to `Q8_1$14`
* New variable `N9` - number of hh members that have moved out that are grandchildren - relationship value from  `Q8_1$1` to `Q8_1$14`
* New variable `N10` - number of hh members that have moved out that are children-in-law - relationship value from  `Q8_1$1` to `Q8_1$14`
* New variable `N11` - number of hh members that have moved out that are parents - relationship value from  `Q8_1$1` to `Q8_1$14`
* New variable `N12` - number of hh members that have moved out that are parents-in-law - relationship value from  `Q8_1$1` to `Q8_1$14`
* New variable `N13` - number of hh members that have moved out that are siblings - relationship value from  `Q8_1$1` to `Q8_1$14`
* New variable `N14` - number of hh members that have moved out that are other family members - relationship value from  `Q8_1$1` to `Q8_1$14`
* New variable `N15` - number of hh members that have moved out that are other non-family members - relationship value from  `Q8_1$1` to `Q8_1$14`
* New variable `N16` - number of hh members that have moved out that are Male - gender from  `Q8_2$1` to `Q8_2$14`
* New variable `N17` - number of hh members that have moved out that are female - gender from  `Q8_2$1` to `Q8_2$14`
* New variable `N18` - number of hh members that have moved out for employment/search for employment - reason from  `Q8_4$1` to `Q8_4$14`
* New variable `N19` - number of hh members that have moved out for education - reason from  `Q8_4$1` to `Q8_4$14`
* New variable `N20` - number of hh members that have moved out for marriage - reason from  `Q8_4$1` to `Q8_4$14`
* New variable `N21` - number of hh members that have moved out followed family - reason from  `Q8_4$1` to `Q8_4$14`
* New variable `N22` - number of hh members that have moved out because of conflict - reason from  `Q8_4$1` to `Q8_4$14`
* New variable `N23` - number of hh members that have moved out for other reason - become a monk - reason from  `Q8_4$1` to `Q8_4$14`. [Becoming a monk was the only other reason specified]
* New variable `N24` - number of hh members that have moved out into same building but separate household. Based on   `Q8_5$1` to `Q8_5$14`.
* New variable `N25` - number of hh members that have moved out into same village/town in walking distance . Based on  `Q8_5$1` to `Q8_5$14`.
* New variable `N26` - number of hh members that have moved out into same village/town but not in walking distance . Based on  `Q8_5$1` to `Q8_5$14`.
* New variable `N27` - number of hh members that have moved out into  different town/village but close enough for regular visits. Based on   `Q8_5$1` to `Q8_5$14`.
* New variable `N28` - number of hh members that have moved out into nto different town/village but too far for regular visits'. Based on  `Q8_5$1` to `Q8_5$14`.
* New variable `N29` - number of hh members that have moved out into different country. Based on  `Q8_5$1` to `Q8_5$14`.
* **ISSUE** - `Q15`: the question reads "of the largest loan you have taken in the last 12 months, who did you borrow from" - 30 % listed more than one lender? This should not be possible. This also leaves three different"other" answers, particularly unclear how this could happen..
* New variable `N30` - number of lenders listed in answer to question 15. From `Q15_A` to `Q15_J`
* **ISSUE**: variable `Q20_B` shouldn't exist?!
* New variable `N31` - difference between acreage of land owned and that cultivated. `Q17` - `Q18`
* New variable `N32` - difference between acreage of land owned and that cultivated and or leased out. This is land left fallow, so the couple of cases with negative values are errors! [ ISSUE]. `Q17` - `Q18` - `Q20_A`
* New variable `N33` - difference between acreage of land rented and that rented and cultivated rented land left fallow, and tehre is none. `Q22` - `Q23` 

## Monday 6.2.2017 - First trawl - Univariate descriptives - continuted

* Q24B and C ask- who is responsible for managing the farming activities apart from the respondent - hh menber ID. So the in order to get relationship etc. of these people new variables are required. 
* New variable `N34` - Relationship of co-responsible manager. Form `Q24_B_ID`
* **ISSUE** - N34 should not have the value 1 = self. Becasue that means they have answered "me and another family member" and the other family memeber is me. But there are 6 such people.
* New variable `N35` - Relationship ofother household member that is listed as responsible for farm management.  Form `Q24_C_ID`
* Check that N34 and N35 have no overlapp, correct.
* New variable `N36` - relationship of other household memebr that is either co- or solely responsible for farm management.  form `N34` and `N35`
* Check that Q25 "used to manage" is asked of right people - those who say now other family member manages in Q24. correct. 
* Check that Q26 "when used to manage" is asked of right people - those who said they used to manage in Q25. correct. 
* Check that Q27 "go check the field daily" is asked of right people, those that said they manage or co-manage in Q24. correct. 
* Q28 question "when no longer able to visit land" - each option is coded as separate variables for yes/no and tehn for relationship. Instead I merge them.
* New variable `N37` - "Will co-manage with child(-in-law)" from `Q28_A` and `Q28_A_OT_SP`. 
* New variable `N38` - "Will hand over to child(-in-law)" from `Q28_B` and `Q28_B_OT_SP`. 
* New variable `N39` - "Will co-manage with other relative" from `Q28_C` and `Q28_C_OT_SP`. 
* New variable `N40` - "Will hand over to other relative" from `Q28_D` and `Q28_D_OT_SP`. 
* New variable `N41` - "Will do something else" from `Q28_G` and `Q28_G_OT_SP`. 
* **ISSUE** - Q28 should have had "One option only" - but in the end 31 people gave two options. 
* New variable `N46` - how Q28 should look like - with all options given. BUT, because of multiple answers, these are given additionally. (variables N42-N45 are temporary)
* New variable `N47` has the size of your land increased in any way in the past five years from `Q30_A`, `Q30_B`, AND `Q30_C`.  
* New variable `N48` the total acreage of increase - sum of bought, rented and ingherited in from `Q30_A_ACRE`, `Q30_B_ACRE`, AND `Q30_C_ACRE`.  
* New variable `N49` - number of responses on reduction of land size.   `Q31`: this was a multiple response question, but **ISSUE** of the 44 respondents that had had a decrease in land size, all had only one reason (sold, rented, confiscated, gave away or lost to river errosion). This seems unlikely!?

## Tuesday 7.2.2017 - First trawl - Univariate descriptives - continuted

* New variable `N50` - all five Q31_A questions consolidated - "Reason for decrease in farm size in last five years". From `Q31_A1`, `Q31_A2`, `Q31_A3`, `Q31_A4`, `Q31_A5`.
* New variable `N51`- all five Q31_B questions  consolidated - "Total number of acrers of decrease in farm size in last five years."  From `Q31_B1`, `Q31_B2`, `Q31_B3`, `Q31_B4`, `Q31_B5`.
* Resason in Q31 should be single answer. But each is coded as three answers. But still, turns out they were answered only once. So need to colsolidate each of the five sets of variables.. **ISSUE** Instead of five variables there are 20 here..
* New variable `N52` "Reason for selling land" - from  `Q31_C1_1`, `Q31_C1_2`, `Q31_C1_3`, `Q31_C1_3_OT_SP`.
* New variable `N53` "Reason for letting out land" - from  `Q31_C2_1`, `Q31_C2_2`, `Q31_C2_3`, `Q31_C2_3_OT_SP`.
* New variable `N54` "Reason for giving away land" - from  `Q31_C3_1`, `Q31_C3_2`, `Q31_C3_3`, `Q31_C3_3_OT_SP`. **ISSUE** Two people said they gave away land because of debt. This doesn't make sense - this combination of variables should not have occured. 
* New variable `N55` "Reason for confiscation of land" - from  `Q31_C4_1`, `Q31_C4_2`, `Q31_C4_3`, `Q31_C4_3_OT_SP`. **ISSUE** Confusion here: reason for confiscation given as confiscation!? Also the reason given as "rob" is not clear, was land stolen from someone?
* New variable `N56` "Other reason decrease in land size" - from  `Q31_C5_1`, `Q31_C5_2`, `Q31_C5_3`, `Q31_C4_3_OT_SP`.
* New variabel `N57` "Reason for decrease in land size " - from all 20 `Q31_C` variables consolidated. 
* **ISSUE** All 9 Yes No questions under 'Q32' are coded Yes = 1 and No = 2 Instead of No = 0..
* New variable `N59` "type of crop production for first crop" - what type of combinaiton of subsistence, animal feed and sale from `Q32_1_1` to `Q32_1_3`.
* New variable `N61` "type of crop production for second crop" - what type of combinaiton of subsistence, animal feed and sale from `Q32_2_1` to `Q32_2_3`.
* New variable `N63` "type of crop production for third crop" - what type of combinaiton of subsistence, animal feed and sale from `Q32_3_1` to `Q32_3_3`.
* New variable `N64` "Do you personaly perform land preparation (ploughing) and if not anymore, how long ago did you stop?". Consolidated from `Q33_A` and `Q33_A1`. 
* New variable `N65` "Do you personaly perform harvesting and if not anymore, how long ago did you stop?". Consolidated from `Q33_B` and `Q33_B1`. 
* New variable `N66` "Do you personaly perform sowing, planting, transplanting and if not anymore, how long ago did you stop?". Consolidated from `Q33_C` and `Q33_C1`. 
* New variable `N67` "Do you personaly perform weeding and if not anymore, how long ago did you stop?". Consolidated from `Q33_D` and `Q33_D1`. 
* New variable `N68` "Do you personaly perform pest management and if not anymore, how long ago did you stop?". Consolidated from `Q33_E` and `Q33_E1`. 

## Wednesday 8.2.2017 - First trawl - Univariate descriptives - continuted

* **ISSUE** Variables `Q34` - all the ID ones (which HH member helps with task) - have the value 0 for the first of five people where there is no one helping instead of a missing value. 
* New variable `N69` "Number of household members (maximum 5) that help with land preparation/ploughing." From vars `Q34_A1_2_ID` `Q34_A2_2_ID` `Q34_A3_2_ID` `Q34_A4_2_ID` and `Q34_A5_2_ID`. 
* New variable `N70` "Total number of days HH members helped with land preparation/ploughing." From vars `Q34_A1_3_DAYS` `Q34_A2_3_DAYS` `Q34_A3_3_DAYS` `Q34_A4_3_DAYS` and `Q34_A5_3_DAYS`. 
* New variable `N71` "Relationship of first HH member who helped with land preparation/ploughing." From vars `Q34_A1_2_ID` ans all the `Q7_2`s for looking up each ID. 
* New variable `N72` "Relationship of second HH member who helped with land preparation/ploughing." From vars `Q34_A2_2_ID` ans all the `Q7_2`s for looking up each ID
* New variable `N73` "Relationship of third HH member who helped with land preparation/ploughing." From vars `Q34_A3_2_ID` ans all the `Q7_2`s for looking up each ID
* New variable `N74` "Relationship of fourth HH member who helped with land preparation/ploughing." From vars `Q34_A4_2_ID` ans all the `Q7_2`s for looking up each ID
* New variable `N75` "Relationship of fifth HH member who helped with land preparation/ploughing." From vars `Q34_A5_2_ID` ans all the `Q7_2`s for looking up each ID..
* New variable `N76` "Number of household members (maximum 5) that help with harvesting." From vars `Q34_B1_2_ID` `Q34_B2_2_ID` `Q34_B3_2_ID` `Q34_B4_2_ID` and `Q34_B5_2_ID`. 
* New variable `N77` "Total number of days HH members helped with land harvesting." From vars `Q34_B1_3_DAYS` `Q34_B2_3_DAYS` `Q34_B3_3_DAYS` `Q34_B4_3_DAYS` and `Q34_B5_3_DAYS`. 
* New variable `N78` "Relationship of first HH member who helped with harvesting." From vars `Q34_B1_2_ID` ans all the `Q7_2`s for looking up each ID. 
* New variable `N79` "Relationship of second HH member who helped with harvesting." From vars `Q34_B2_2_ID` ans all the `Q7_2`s for looking up each ID
* New variable `N80` "Relationship of third HH member who helped with harvesting." From vars `Q34_B3_2_ID` ans all the `Q7_2`s for looking up each ID
* New variable `N81` "Relationship of fourth HH member who helped with harvesting." From vars `Q34_B4_2_ID` ans all the `Q7_2`s for looking up each ID
* New variable `N82` "Relationship of fifth HH member who helped with harvesting." From vars `Q34_B5_2_ID` ans all the `Q7_2`s for looking up each ID..
* New variable `N83` "Number of household members (maximum 5) that help with sowing, plantint, transplanting" From vars `Q34_C1_2_ID` `Q34_C2_2_ID` `Q34_C3_2_ID` `Q34_C4_2_ID` and `Q34_C5_2_ID`. 
* New variable `N84` "Total number of days HH members helped with land sowing, plantint, transplanting" From vars `Q34_C1_3_DAYS` `Q34_C2_3_DAYS` `Q34_C3_3_DAYS` `Q34_C4_3_DAYS` and `Q34_C5_3_DAYS`. 
* New variable `N85` "Relationship of first HH member who helped with sowing, plantint, transplanting" From vars `Q34_C1_2_ID` ans all the `Q7_2`s for looking up each ID. 
* New variable `N86` "Relationship of second HH member who helped with sowing, plantint, transplanting" From vars `Q34_C2_2_ID` ans all the `Q7_2`s for looking up each ID
* New variable `N87` "Relationship of third HH member who helped with sowing, plantint, transplanting" From vars `Q34_C3_2_ID` ans all the `Q7_2`s for looking up each ID
* New variable `N88` "Relationship of fourth HH member who helped with sowing, plantint, transplanting" From vars `Q34_C4_2_ID` ans all the `Q7_2`s for looking up each ID
* New variable `N89` "Relationship of fifth HH member who helped with sowing, plantint, transplanting" From vars `Q34_C5_2_ID` ans all the `Q7_2`s for looking up each ID..
* New variable `N90` "Number of household members (maximum 5) that help with weeding" From vars `Q34_D1_2_ID` `Q34_D2_2_ID` `Q34_D3_2_ID` `Q34_D4_2_ID` and `Q34_D5_2_ID`. 
* New variable `N91` "Total number of days HH members helped with land weeding" From vars `Q34_D1_3_DAYS` `Q34_D2_3_DAYS` `Q34_D3_3_DAYS` `Q34_D4_3_DAYS` and `Q34_D5_3_DAYS`. 
* New variable `N92` "Relationship of first HH member who helped with weeding" From vars `Q34_D1_2_ID` ans all the `Q7_2`s for looking up each ID. 
* New variable `N93` "Relationship of second HH member who helped with weeding" From vars `Q34_D2_2_ID` ans all the `Q7_2`s for looking up each ID
* New variable `N94` "Relationship of third HH member who helped with weeding" From vars `Q34_D3_2_ID` ans all the `Q7_2`s for looking up each ID
* New variable `N95` "Relationship of fourth HH member who helped with weeding" From vars `Q34_D4_2_ID` ans all the `Q7_2`s for looking up each ID
* New variable `N96` "Relationship of fifth HH member who helped with weeding" From vars `Q34_D5_2_ID` ans all the `Q7_2`s for looking up each ID..
* New variable `N97` "Number of household members (maximum 5) that help with pest management" From vars `Q34_E1_2_ID` `Q34_E2_2_ID` `Q34_E3_2_ID` `Q34_E4_2_ID` and `Q34_E5_2_ID`. 
* New variable `N98` "Total number of days HH members helped with land pest management" From vars `Q34_E1_3_DAYS` `Q34_E2_3_DAYS` `Q34_E3_3_DAYS` `Q34_E4_3_DAYS` and `Q34_E5_3_DAYS`. 
* New variable `N99` "Relationship of first HH member who helped with pest management" From vars `Q34_E1_2_ID` ans all the `Q7_2`s for looking up each ID. 
* New variable `N100` "Relationship of second HH member who helped with pest management" From vars `Q34_E2_2_ID` ans all the `Q7_2`s for looking up each ID
* New variable `N101` "Relationship of third HH member who helped with pest management" From vars `Q34_E3_2_ID` ans all the `Q7_2`s for looking up each ID
* New variable `N102` "Relationship of fourth HH member who helped with pest management" From vars `Q34_E4_2_ID` ans all the `Q7_2`s for looking up each ID
* New variable `N103` "Total number of days HH members helped with all 5 types of farm activities" from `N70`, `N77`, `N84`, `N91` and `N98`
* **ISSUE** `Q35` and q36 are incompatible? In fact q35 asking 'did you hire from this village' is impossible to answer if the person hired both. How did this happent, how was it not addressed in the pilot and how was it finally solved?
* New variable `N104` -  "In the last 12 months did you hire labour to help with any of following the farming tasks? {Land preparation/Ploughing} and if yes, were they from the same village" - From `Q35_A_1` `Q35._A_2`
* New variable `N105` -  "In the last 12 months did you hire labour to help with any of following the farming tasks? {Harvesting} and if yes, were they from the same village" - From `Q35_B_1` `Q35._B_2`
* New variable `N106` -  "In the last 12 months did you hire labour to help with any of following the farming tasks? {Sowing, planting, transplanting} and if yes, were they from the same village" -From `Q35_C_1` `Q35_C_2`
* New variable `N107` -  "In the last 12 months did you hire labour to help with any of following the farming tasks? {Weeding} and if yes, were they from the same village" From `Q35_D_1` `Q35_D_2`
* New variable `N108` -  "In the last 12 months did you hire labour to help with any of following the farming tasks? {Managing pests} and if yes, were they from the same village" - From  `Q35_E_1` `Q35_E_2`
* **ISSUE** all 10 `q36` variables: number of person/days are zero, not missing..
* New variable `N109` "What were the total number of person-days employed in the last 12 months for each of the following tasks:From local village Days {Land preparation/Ploughing}" From `Q36_A1` but without the zeros.
* New variable `N110` "What were the total number of person-days employed in the last 12 months for each of the following tasks:NOT From local village Days {Land preparation/Ploughing}" From `Q36_A2` but without the zeros.
* New variable `N111` "What were the total number of person-days employed in the last 12 months for each of the following tasks:From local village Days {Harvesting}" From `Q36_B1` but without the zeros.
* New variable `N112` "What were the total number of person-days employed in the last 12 months for each of the following tasks:NOT From local village Days {Harvesting}" From `Q36_B2` but without the zeros.

## Thursday 10.2.2017 - First trawl - Univariate descriptives - continuted

* New variable `N113` "What were the total number of person-days employed in the last 12 months for each of the following tasks:From local village Days {sowing, planting, transplanting}" From `Q36_C1` but without the zeros.
* New variable `N114` "What were the total number of person-days employed in the last 12 months for each of the following tasks:NOT From local village Days {sowing, planting, transplanting}" From `Q36_C2` but without the zeros.
* New variable `N115` "What were the total number of person-days employed in the last 12 months for each of the following tasks:From local village Days {Weeding}" From `Q36_D1` but without the zeros.
* New variable `N116` "What were the total number of person-days employed in the last 12 months for each of the following tasks:NOT From local village Days {Weeding}" From `Q36_D2` but without the zeros.
* New variable `N117` "What were the total number of person-days employed in the last 12 months for each of the following tasks:From local village Days {Pest management}" From `Q36_E1` but without the zeros.
* New variable `N118` "What were the total number of person-days employed in the last 12 months for each of the following tasks:NOT From local village Days {Pest management}" From `Q36_E2` but without the zeros.
* New variable `N119` "What were the total number of person-days employed in the last 12 months for all five tasks: From local village." From `N109`, `N111`, `N113`, `N115`, `N117`.
* New variable `N120` "What were the total number of person-days employed in the last 12 months for all five tasks: NOT From local village." From `N110`, `N112`, `N114`, `N116`, `N118`.
* New variable `N121` "What were the total number of person-days employed in the last 12 months for all five tasks: from anywhere." From `N119`, `N120.
* **ISSUE** again variables Q37_A to Q37_J are coded as 2 for 'No' instead of 0. Recoded all into same variables. 
* New variable `N122` - "Total number of novel farming methods tried in the last two years (out of the 10 listed)." From vars `Q37_A` to `Q37_J`.
* New variable `N123` - Those that had received advice form the Agricultural services "Did they receive information on planting new crops and if yes, did they act on it?" From vars `Q39_A1` and `Q39_A2`. 
* New variable `N124` - Those that had received advice form the Agricultural services "Did they receive information on new seed varieties and if yes, did they act on it?" From vars `Q39_B1` and `Q39_B2`. 
* New variable `N125` - Those that had received advice form the Agricultural services "Did they receive information oninter-cropping or mixed cropping and if yes, did they act on it?" From vars `Q39_C1` and `Q39_C2`. 
* New variable `N126` - Those that had received advice form the Agricultural services "Did they receive information on double cropping on the same plot  and if yes, did they act on it?" From vars `Q39_D1` and `Q39_D2`. 
* New variable `N127` - Those that had received advice form the Agricultural services "Did they receive information on plant spacing and if yes, did they act on it?" From vars `Q39_E1` and `Q39_E2`. 
* New variable `N128` - Those that had received advice form the Agricultural services "Did they receive information on managing pests and/or use of pesticides and if yes, did they act on it?" From vars `Q39_F1` and `Q39_F2`. 
* New variable `N129` - Those that had received advice form the Agricultural services "Did they receive information on fertilisers and if yes, did they act on it?" From vars `Q39_G1` and `Q39_G2`. 
* New variable `N130` - Those that had received advice form the Agricultural services "Did they receive information on the use of farm machinery and if yes, did they act on it?" From vars `Q39_H1` and `Q39_H2`. 
* New variable `N131` - Those that had received advice form the Agricultural services "Did they receive information on water management and if yes, did they act on it?" From vars `Q39_H1` and `Q39_H2`. 
* New variable `N132` - "Tell me which of those sources of your knowledge for faming are? {Other Specified options" From `Q40_I` and `Q40_I_OT_SP`. 
* **ISSUE** - Q40_1, Q40_2 and Q40_3 could have the "other specify" options merged togehter instead of separate variables. 
* New variable `N133` - "And which one is the most important source of your knowledge for farming?" - merge with 'other specify' options `Q40_1` and `Q40_1_OT_SP`.
* New variable `N134` - " And which one is the second most important source of your knowledge for farming?" - merge with 'other specify' options `Q40_2` and `Q40_2_OT_SP`.
* New variable `N135` - "And which one is the third most important source of your knowledge for farming?" - merge with 'other specify' options `Q40_3` and `Q40_3_OT_SP`.
* **ISSUE** - `Q43_1` and `Q43_2` could have the "other specify" options merged together instead of separate variables. 
* New variable `N136` - "Which one is the most important reason your corp yields are increasing?" From merge with 'other specify' options `Q43_1` and `Q43_1_OT_SP`.
* New variable `N137` - "Which one is the second most important reason your corp yields are increasing?" From merge with 'other specify' options `Q43_2` and `Q43_2_OT_SP`.
* **ISSUE** - `Q44_1` and `Q44_2` could have the "other specify" options merged together instead of separate variables. 
* New variable `N138` - "Which one is the most important reason your corp yields are decreasing?" From merge with 'other specify' options `Q44_1` and `Q44_1_OT_SP`.
* New variable `N139` - "Which one is the second most important reason your corp yields are decreasing?" From merge with 'other specify' options `Q44_2` and `Q44_2_OT_SP`.
* **ISSUE** Q45 was only asked of people who answered increase or decrease in Q43, others went straight on to Module 3.. Nothing to be done.. 
* **ISSUE** - `Q45_1` and `Q45_2` could have the "other specify" options merged together instead of separate variables. 
* New variable `N140` - "Which one is the most important challenge to you farming ?" From merge with 'other specify' options `Q45_1` and `Q45_1_OT_SP`.
* New variable `N141` - "Which one is the second most important challenge to you farming?" From merge with 'other specify' options `Q45_2` and `Q45_2_OT_SP`
* **ISSUE** `Q46_1_OT_SP` has the option "Late time line of farm work" not sure what that means?
* **ISSUE** some more unclear translations in `q46_1_OT_SP`
* New variable `N142` - "Which one is the most important challenge to farming for the community as a whole?" From merge with 'other specify' options `Q46_1` and `Q46_1_OT_SP`.
* New variable `N143` - "Which one is the second most important challenge to farming for the community as a whole?" From merge with 'other specify' options `Q46_2` and `Q46_2_OT_SP`
* New variable `N144` - "Which one is the third most important challenge to farming for the community as a whole?" From merge with 'other specify' options `Q46_3` and `Q46_3_OT_SP`


